/*
 * This source file was generated by the Gradle 'init' task
 */
package com.checkoutKata;
import com.checkoutkata.CheckoutEngine;
import com.checkoutkata.RegularPricingRule;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeEach;

import java.util.HashMap;
import java.util.Map;

public class CheckoutTest {

    private Map<Character, RegularPricingRule> pricingRules;

    @BeforeEach
    public void setUp() {
        pricingRules = new HashMap<>();
        pricingRules.put('A', new RegularPricingRule(50));
        pricingRules.put('B', new RegularPricingRule(30));
    }

    @Test
    public void totalPriceOfZeroItem() {
        CheckoutEngine checkoutEngine = new CheckoutEngine(pricingRules);
        checkoutEngine.scan("");
        assertEquals(0, checkoutEngine.getTotal());
    }

    @Test
    public void totalPriceOfOneItem() {
        CheckoutEngine checkoutEngine = new CheckoutEngine(pricingRules);
        checkoutEngine.scan("A");
        assertEquals(50, checkoutEngine.getTotal());
    }

    @Test
    public void totalPriceOfTwoItem() {
        CheckoutEngine checkoutEngine = new CheckoutEngine(pricingRules);
        checkoutEngine.scan("AB");
        assertEquals(80, checkoutEngine.getTotal());
    }

}
