/*
 * This source file was generated by the Gradle 'init' task
 */
package com.checkoutKata;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class CheckoutTest {
    @Test
    void basicTest() {
        assertEquals(2, 1 + 1);
    }
}
