/*
 * This source file was generated by the Gradle 'init' task
 */
package com.checkoutkata;

import java.util.HashMap;
import java.util.Map;

public class CheckoutEngine {

    private Map<Character, Integer> itemToCountMap;

    public CheckoutEngine() {
        itemToCountMap = new HashMap<>();
    }

    public void scan(String items) {
        if (items == null || items.isEmpty()) {
            return;
        }

        for (char item : items.toCharArray()) {
            itemToCountMap.put(item, itemToCountMap.getOrDefault(item, 0) + 1);
        }
    }

    public int getTotal() {
        int total = 0;

        for (Map.Entry<Character, Integer> entry : itemToCountMap.entrySet()) {
            int count = entry.getValue();
            int price = 50;
            total += price * count;
        }
        
        return total;
    }

}
