/*
 * This source file was generated by the Gradle 'init' task
 */
package com.checkoutkata;

import java.util.HashMap;
import java.util.Map;

public class CheckoutEngine {
    private Map<Character, RegularPricingRule> pricingRules;
    private Map<Character, Integer> itemToQuantityMap;

    public CheckoutEngine(Map<Character, RegularPricingRule> pricingRules) {
        this.itemToQuantityMap = new HashMap<>();
        this.pricingRules = pricingRules;
    }

    public void scan(String items) {
        if (items == null || items.isEmpty()) {
            return;
        }

        for (char item : items.toCharArray()) {
            itemToQuantityMap.put(item, itemToQuantityMap.getOrDefault(item, 0) + 1);
        }
    }

    public int getTotal() {
        int total = 0;

        for (Character item : itemToQuantityMap.keySet()) {
            int quantity = itemToQuantityMap.get(item);
            RegularPricingRule rule = pricingRules.get(item);
            total += rule.calculatePrice(quantity);
        }

        return total;
    }

}
